apiVersion: apps/v1
kind: Deployment
metadata:
  name: 737kubernetes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 737kubernetes
  template:
    metadata:
      labels:
        app: 737kubernetes
    spec:
      containers:
      - name: 737kubernetes
        image: abhishek2806/737kubernetes-image:v2
        ports:
        - containerPort: 3000
