apiVersion: v1
kind: Service
metadata:
  name: kube737-service
spec:
  type: NodePort
  selector:
    app: 737kubernetes
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
